model_type: logistic_regression

scoring: roc_auc
cv: 5

param_grid:
  - model__solver:
      - liblinear

    model__l1_ratio:
      - 0.0
      - 1.0

    model__C:
      - 0.01
      - 0.1
      - 1
      - 10
      - 100

    model__class_weight:
      - null
      - balanced

  - model__solver:
      - lbfgs

    model__l1_ratio:
      - 0.0

    model__C:
      - 0.01
      - 0.1
      - 1
      - 10
      - 100

    model__class_weight:
      - null
      - balanced