model_type: random_forest

model_params:
  max_depth: 10
  max_features: sqrt
  min_samples_leaf: 10
  min_samples_split: 2
  n_estimators: 200
  random_state: 42
  n_jobs: -1

calibration:
  method: none
  cv: 5
  ensemble: false


threshold: 0.5